### ISSUE TITLE
Download link not working for MacOSX

### ISSUE THREAD

**Issue by kinshuk4** [0x3333/wmail-reloaded#1]
* Which version of WMail are you using? Ans - [2.3]

* Which Operating System are you using? Ans [Mac OSX 10]

Hi,
   Thanks for creating the app. The download link is not working for the app. can you please help :)

**Comment by 0x3333** [comment]
Hi!

Try using this version:
[https://github.com/openWMail/openWMail](https://github.com/openWMail/openWMail)

My version is behind it.

Thanks.

**Comment by kinshuk4** [comment]
Thanks. 👍
